### ISSUE TITLE
接口文档疑问？

### ISSUE THREAD

**Issue by maobi6301** [hi-sb/io-tail#2]
### 接口问题

- 签名 **AUTH_TOKEN**，请提供文档说明怎么解签，获取NickName, Avator, UserID等用户基本信息；
- 请求与响应是否有加密信息，如有请在在文档接口说明，如是通用请提供案列
- 接口 **1.1 获取短信验证码** 返回值说明下是否需要用
- 接口 **1.2 与 1.3** 接口一样，请检查是否正确；
- 接口 **3.3 获取群信息**，请再额外添加一个用户在群的角色字段**GroupMemberRole** 
- 接口 **3.5 剔除成员** 中参数**userId**,是否是**UserID**
- 接口 **3.10 根据群昵称查询成员信息** 前端应该不会用，查询群基本信息里面有全部用户数据，直接本地数据过滤即可
- 检查是否禁言与是否属于黑名单，应该发送消息后端验证（**5.3，5.4**等）

### 接口建议
请提供**特殊验证码**如888888，没有那么多手机提供测试，服务端配置2个参数，**特殊验证码启用/禁用状态**，**特殊验证码值**，非**生产模式**启用**特殊验证码**

**Comment by maobi6301** [comment]
### 接口问题
- **2.3  更新添加好友状态（拒绝/同意)** 中的申请编号**ID** 在 **2.2 获取当前用户添加好友的请求**
没有找到该字段
- ** 有木有设计像微信一样**未读**_小红点数字显示_

### 寻求帮助
- 请提供一份长连接客户端代码，方便沟通，语言可以用js(ts)/java/kotlin/dart提供案例
- 监听长连接，多个**两两私人对话，用一个连接**；群组对话，**每个群组建立一个连接**，_那本地已存在多个群组聊天对话，是不是就要监听多个群组长连接_，这方面性能是否可以通过压测。

**Comment by mr-gaochen** [comment]
> ### 接口问题
> * 签名 **AUTH_TOKEN**，请提供文档说明怎么解签，获取NickName, Avator, UserID等用户基本信息；
> * 请求与响应是否有加密信息，如有请在在文档接口说明，如是通用请提供案列
> * 接口 **1.1 获取短信验证码** 返回值说明下是否需要用
> * 接口 **1.2 与 1.3** 接口一样，请检查是否正确；
> * 接口 **3.3 获取群信息**，请再额外添加一个用户在群的角色字段**GroupMemberRole**
> * 接口 **3.5 剔除成员** 中参数**userId**,是否是**UserID**
> * 接口 **3.10 根据群昵称查询成员信息** 前端应该不会用，查询群基本信息里面有全部用户数据，直接本地数据过滤即可
> * 检查是否禁言与是否属于黑名单，应该发送消息后端验证（**5.3，5.4**等）
> 
> ### 接口建议
> 请提供**特殊验证码**如888888，没有那么多手机提供测试，服务端配置2个参数，**特殊验证码启用/禁用状态**，**特殊验证码值**，非**生产模式**启用**特殊验证码**


接口文档有更新，你可以先更新下

**Comment by mr-gaochen** [comment]
> ### 接口问题
> * 签名 **AUTH_TOKEN**，请提供文档说明怎么解签，获取NickName, Avator, UserID等用户基本信息；
> * 请求与响应是否有加密信息，如有请在在文档接口说明，如是通用请提供案列
> * 接口 **1.1 获取短信验证码** 返回值说明下是否需要用
> * 接口 **1.2 与 1.3** 接口一样，请检查是否正确；
> * 接口 **3.3 获取群信息**，请再额外添加一个用户在群的角色字段**GroupMemberRole**
> * 接口 **3.5 剔除成员** 中参数**userId**,是否是**UserID**
> * 接口 **3.10 根据群昵称查询成员信息** 前端应该不会用，查询群基本信息里面有全部用户数据，直接本地数据过滤即可
> * 检查是否禁言与是否属于黑名单，应该发送消息后端验证（**5.3，5.4**等）
> 
> ### 接口建议
> 请提供**特殊验证码**如888888，没有那么多手机提供测试，服务端配置2个参数，**特殊验证码启用/禁用状态**，**特殊验证码值**，非**生产模式**启用**特殊验证码**

3.3中的问题已经解决了
3.5 userID 是剔除者的id

**Comment by mr-gaochen** [comment]
> ### 接口问题
> * **2.3  更新添加好友状态（拒绝/同意)** 中的申请编号**ID** 在 **2.2 获取当前用户添加好友的请求**
>   没有找到该字段
> * ** 有木有设计像微信一样**未读**_小红点数字显示_
> 
> ### 寻求帮助
> * 请提供一份长连接客户端代码，方便沟通，语言可以用js(ts)/java/kotlin/dart提供案例
> * 监听长连接，多个**两两私人对话，用一个连接**；群组对话，**每个群组建立一个连接**，_那本地已存在多个群组聊天对话，是不是就要监听多个群组长连接_，这方面性能是否可以通过压测。

**Comment by hi-sb** [comment]
5.3 ,5.4 关于黑名单和好友关系验证，在每次发送消息时都会在后端验证。前端无需关心验证问题。

对每个人而言，他拥有一个私有的长链接来监听自己的私有消息。
而群会话，每个群会话维护一个长链接。单服务1c 1g io型机器可以支撑10w+的链接，更大的陪练测试就没有做了。
如果链接超过十万个的时候出现瓶颈则重新开一台机器做集群话处理，维护更多的链接就好了。这样做的目的在于可以更方便的维护话题文件，对不同对话题做分布式部署。

**Comment by hi-sb** [comment]
稍后我将在这里回复 java 版本的消息收发示例代码。

**Comment by maobi6301** [comment]
文档昨晚过后，没有更新
